Add smb shares, cleanup + improvements, Chromium -> Google Chrome (#23)

diff --git a/.github/workflows/fedora.yml b/.github/workflows/fedora.yml
--- a/.github/workflows/fedora.yml
+++ b/.github/workflows/fedora.yml
@@ -38,7 +38,7 @@ jobs:
     steps:
       - uses: actions/checkout@v2
 
-      - name: Install packages
+      - name: Install brew packages
         run: |
           brew install ansible gnu-sed hudochenkov/sshpass/sshpass
 
@@ -58,3 +58,15 @@ jobs:
       - name: Ansible
         run: |
           ansible-playbook --user="${MYUSER}" --skip-tags data,interactive,secrets,skip_test,test_data --extra-vars "ansible_password=${PASSWORD} ansible_become_password=${PASSWORD} ansible_python_interpreter=/usr/bin/python3" main.yml -i "127.0.0.1,"
+
+      - name: Ansible 2
+        run: |
+          ansible-playbook --user="${MYUSER}" --skip-tags data,interactive,secrets,skip_test,test_data --extra-vars "ansible_password=${PASSWORD} ansible_become_password=${PASSWORD} ansible_python_interpreter=/usr/bin/python3" main.yml -i "127.0.0.1," | tee /tmp/ansible.log
+          if grep -q 'changed=0.*failed=0' /tmp/ansible.log ; then
+            echo 'Idempotence test: pass'
+            exit 0
+          else
+            echo 'Idempotence test: fail'
+            grep -B 2 '^changed:' /tmp/ansible.log
+            exit 1
+          fi
