feat(upgrade): upgrade to MacBook Air and macOS 14
BREAKING CHANGE: 🧨 yes

diff --git a/.github/workflows/fedora.yml b/.github/workflows/fedora.yml
--- a/.github/workflows/fedora.yml
+++ b/.github/workflows/fedora.yml
@@ -43,22 +43,25 @@ jobs:
 
       - name: Add main user to Fedora VirtualBox VM
         run: |
+          cd ansible || exit
           echo "${PASSWORD}" > vault-my_workstation.password
           ansible --become --user vagrant --connection-password-file=vault-my_workstation.password --become-password-file=vault-my_workstation.password -m user -a "name=${MYUSER} password={{ \"${PASSWORD}\" | password_hash }} append=yes groups=wheel" -i "127.0.0.1," 127.0.0.1
 
       - name: Ansible
         run: |
-          ansible-playbook --user="${MYUSER}" --skip-tags data,interactive,secrets,skip_test,test_data --connection-password-file=vault-my_workstation.password --become-password-file=vault-my_workstation.password main.yml -i "127.0.0.1,"
+          cd ansible || exit
+          ansible-playbook --user="${MYUSER}" --skip-tags data,interactive,secrets,skip_test --connection-password-file=vault-my_workstation.password --become-password-file=vault-my_workstation.password main.yml -i "127.0.0.1,"
 
-      # - name: Ansible - Idempotence tests
-      #   run: |
-      #     ansible-playbook --user="${MYUSER}" --skip-tags data,interactive,secrets,skip_test,test_data --extra-vars "ansible_password=${PASSWORD} ansible_become_password=${PASSWORD}" main.yml -i "127.0.0.1," | tee /tmp/ansible.log
-      #     # https://stackoverflow.com/questions/59361798/github-actions-functions-on-the-console-output
-      #     if [ "$(grep -c 'changed=0.*failed=0' /tmp/ansible.log)" = "1" ] ; then
-      #       echo -e '\nIdempotence test: pass'
-      #       exit 0
-      #     else
-      #       echo -e '\nIdempotence test: fail\n'
-      #       grep -B 2 '^changed:' /tmp/ansible.log
-      #       exit 1
-      #     fi
+      - name: Ansible - Idempotence tests
+        run: |
+          cd ansible || exit
+          ansible-playbook --user="${MYUSER}" --skip-tags data,interactive,secrets,skip_test --extra-vars "ansible_password=${PASSWORD} ansible_become_password=${PASSWORD}" main.yml -i "127.0.0.1," | tee /tmp/ansible.log
+          # https://stackoverflow.com/questions/59361798/github-actions-functions-on-the-console-output
+          if [ "$(grep -c 'changed=0.*failed=0' /tmp/ansible.log)" = "1" ] ; then
+            echo -e '\nIdempotence test: pass'
+            exit 0
+          else
+            echo -e '\nIdempotence test: fail\n'
+            grep -B 2 '^changed:' /tmp/ansible.log
+            exit 1
+          fi
diff --git a/.github/workflows/macos.yml b/.github/workflows/macos.yml
--- a/.github/workflows/macos.yml
+++ b/.github/workflows/macos.yml
@@ -20,8 +20,8 @@ env:
 
 jobs:
   macos:
-    runs-on: macos-12
-    timeout-minutes: 150
+    runs-on: macos-13
+    timeout-minutes: 100
     steps:
       - uses: actions/checkout@v4
 
@@ -31,19 +31,20 @@ jobs:
 
       - name: Ansible
         run: |
+          cd ansible || exit
           echo "test_password" > vault-my_workstation.password
-          ansible-playbook --skip-tags data,interactive,secrets,skip_test,test_data --connection=local -i "127.0.0.1," main.yml
+          ansible-playbook --skip-tags data,interactive,secrets,skip_test --connection=local -i "127.0.0.1," main.yml
 
-      # - name: Ansible - Idempotence tests
-      #   run: |
-      #     set -x
-      #     ansible-playbook --skip-tags data,interactive,secrets,skip_test,test_data -e 'ansible_python_interpreter=/usr/local/bin/python3' --connection=local -i "127.0.0.1," main.yml | tee /tmp/ansible.log
-      #     # https://stackoverflow.com/questions/59361798/github-actions-functions-on-the-console-output
-      #     if [ "$(grep -c 'changed=0.*failed=0' /tmp/ansible.log)" = "1" ] ; then
-      #       echo -e '\nIdempotence test: pass'
-      #       exit 0
-      #     else
-      #       echo -e '\nIdempotence test: fail\n'
-      #       grep -B 2 '^changed:' /tmp/ansible.log
-      #       exit 1
-      #     fi
+      - name: Ansible - Idempotence tests
+        run: |
+          cd ansible || exit
+          ansible-playbook --skip-tags data,interactive,secrets,skip_test --connection=local -i "127.0.0.1," main.yml | tee /tmp/ansible.log
+          # https://stackoverflow.com/questions/59361798/github-actions-functions-on-the-console-output
+          if [ "$(grep -c 'changed=0.*failed=0' /tmp/ansible.log)" = "1" ] ; then
+            echo -e '\n✅ Idempotence test: pass'
+            exit 0
+          else
+            echo -e '\n❗️ Idempotence test: fail\n'
+            grep -B 2 '^changed:' /tmp/ansible.log
+            exit 1
+          fi
